name: 'Staging Provisioning'

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]
  workflow_dispatch:    # No inputs needed, just manual trigger

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: staging    # Single environment

    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Create Backend Config
      run: |
        cat > backend.hcl << EOF
        access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
        secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        skip_credentials_validation = true
        skip_region_validation = true
        skip_metadata_api_check = true
        use_path_style = true
        disable_aws_client_checksums = true
        EOF

    - name: Terraform Init with Local Backend
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      run: |
        # Create a local backend override
        cat > override.tf << EOF
        terraform {
          backend "local" {}
        }
        EOF
        
        # Initialize with local backend
        terraform init -reconfigure

    - name: Terraform Format
      run: terraform fmt

    - name: Update Resource Names
      run: |
        # Add timestamp to resource names to make them unique
        TIMESTAMP=$(date +%s)
        
        # Update SSH key name
        sed -i "s/resource \"hcloud_ssh_key\" \"default\"/resource \"hcloud_ssh_key\" \"key_$TIMESTAMP\"/" main.tf
        sed -i "s/hcloud_ssh_key.default/hcloud_ssh_key.key_$TIMESTAMP/g" main.tf
        
        # Update firewall name
        sed -i "s/resource \"hcloud_firewall\" \"default\"/resource \"hcloud_firewall\" \"fw_$TIMESTAMP\"/" main.tf
        sed -i "s/hcloud_firewall.default/hcloud_firewall.fw_$TIMESTAMP/g" main.tf

    - name: Terraform Plan
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_database_url: ${{ secrets.DATABASE_URL }}
        TF_VAR_redis_url: ${{ secrets.REDIS_URL }}
        TF_VAR_registry_username: ${{ secrets.REGISTRY_USERNAME }}
        TF_VAR_registry_password: ${{ secrets.REGISTRY_PASSWORD }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        TF_VAR_server_name: "kerry-server"
        TF_VAR_server_type: "cx22"
        TF_VAR_staging_username: ${{ secrets.STAGING_USERNAME }}
        TF_VAR_staging_password: ${{ secrets.STAGING_PASSWORD }}
        TF_VAR_cloudflare_cert: ${{ secrets.CLOUDFLARE_CERT }}
        TF_VAR_cloudflare_key: ${{ secrets.CLOUDFLARE_KEY }}
        TF_VAR_frontend_repo_url: ${{ secrets.FRONTEND_REPO_URL }}
        TF_VAR_backend_repo_url: ${{ secrets.BACKEND_REPO_URL }}
        TF_VAR_frontend_image_tag: ${{ secrets.FRONTEND_IMAGE_TAG }}
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_database_url: ${{ secrets.DATABASE_URL }}
        TF_VAR_redis_url: ${{ secrets.REDIS_URL }}
        TF_VAR_registry_username: ${{ secrets.REGISTRY_USERNAME }}
        TF_VAR_registry_password: ${{ secrets.REGISTRY_PASSWORD }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        TF_VAR_server_name: "kerry-server"
        TF_VAR_server_type: "cx22"
        TF_VAR_staging_username: ${{ secrets.STAGING_USERNAME }}
        TF_VAR_staging_password: ${{ secrets.STAGING_PASSWORD }}
        TF_VAR_cloudflare_cert: ${{ secrets.CLOUDFLARE_CERT }}
        TF_VAR_cloudflare_key: ${{ secrets.CLOUDFLARE_KEY }}
        TF_VAR_frontend_repo_url: ${{ secrets.FRONTEND_REPO_URL }}
        TF_VAR_backend_repo_url: ${{ secrets.BACKEND_REPO_URL }}
        TF_VAR_frontend_image_tag: ${{ secrets.FRONTEND_IMAGE_TAG }}
      run: terraform apply -auto-approve -input=false