name: 'Terraform'

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      server_name:
        description: 'Server name'
        required: true
        default: 'kerry-staging'
        type: string
      server_type:
        description: 'Server type'
        required: true
        default: 'cx22'
        type: string

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}

    if: |
      github.event_name == 'workflow_dispatch' ||
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/staging'

    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Create Backend Config
      run: |
        cat > backend.hcl << EOF
        access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
        secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        EOF

    - name: Terraform Init
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "eu-central-1"
      run: |
        cat > backend.hcl << EOF
        access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
        secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        EOF
        terraform init -backend-config=backend.hcl

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        TF_VAR_server_name: ${{ github.event.inputs.server_name || (github.ref == 'refs/heads/main' && 'kerry-production' || 'kerry-staging') }}
        TF_VAR_server_type: ${{ github.event.inputs.server_type || 'cpx21' }}
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        TF_VAR_server_name: ${{ github.event.inputs.server_name || (github.ref == 'refs/heads/main' && 'kerry-production' || 'kerry-staging') }}
        TF_VAR_server_type: ${{ github.event.inputs.server_type || 'cpx21' }}
      run: terraform apply -auto-approve -input=false