name: 'Terraform'

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]
  workflow_dispatch:    # No inputs needed, just manual trigger

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: staging    # Single environment

    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Create Backend Config
      run: |
        cat > backend.hcl << EOF
        access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
        secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        EOF

    - name: Terraform Init
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "eu-central-1"
      run: |
        cat > backend.hcl << EOF
        access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
        secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        EOF
        terraform init -backend-config=backend.hcl

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Plan
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        TF_VAR_server_name: "kerry-server"
        TF_VAR_server_type: "cx22"
        TF_VAR_staging_username: ${{ secrets.STAGING_USERNAME }}
        TF_VAR_staging_password: ${{ secrets.STAGING_PASSWORD }}
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        TF_VAR_server_name: "kerry-server"
        TF_VAR_server_type: "cx22"
        TF_VAR_staging_username: ${{ secrets.STAGING_USERNAME }}
        TF_VAR_staging_password: ${{ secrets.STAGING_PASSWORD }}
      run: terraform apply -auto-approve -input=false